In [1]:
import numpy as np

# Evaluacion 3: Cassia Dafoe

## NumPy

1. Importa la librería de NumPy.
2. Crea un array de 1 dimension y 10 elementos.


In [9]:
array1 = np.random.randint(0,100,(10))
array1

array([86, 73, 74, 97, 99, 11,  6, 48,  5,  4])

3. Reemplaza todos los números impares por el valor "par" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [20]:
# para crear un array con valores de tipo strings, creo un array "vacio" de tipo "list" 
# de tipo "string" solo me cogia la primera letra de las palabras par o impar
array2 = np.empty((10), dtype = list)
array2

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [23]:
# con un for loop podemos iterar por el array original y reemplazar los valores segun si se
# pueden dividir por 2 sin resto o no (si son par o no); y segun el resultados reemplazamos
# el valor en la misma posicion del array1 por la palabra apropriada
for i, valor in enumerate(array1):
    if valor % 2 ==0:
        array2[i] = "par"
    else:
        array2[i] = "impar"

In [24]:
array2

array(['par', 'impar', 'par', 'impar', 'impar', 'impar', 'par', 'par',
       'impar', 'par'], dtype=object)

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [25]:
array2 = np.reshape(array2,(2,5))
array2

array([['par', 'impar', 'par', 'impar', 'impar'],
       ['impar', 'par', 'par', 'impar', 'par']], dtype=object)

5. Extrae los elementos comunes de los siguientes arrays

In [27]:
array1a = np.array([1,2,3,2,3,4,3,4,5,6])
array2a = np.array([7,2,10,2,7,4,9,4,9,8])

In [29]:
np.intersect1d(array1a, array2a)

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [30]:
np.setdiff1d(array1a, array2a)

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [42]:
# iteramos por los arrays y los valores que tienen iguales para sacar los indices con np.where
for array in [array1a, array2a]:
    for i in np.intersect1d(array1a, array2a):
        print(f"Los indices del elemento igual {i} son {np.where(array == i)}")

Los indices del elemento igual 2 son (array([1, 3]),)
Los indices del elemento igual 4 son (array([5, 7]),)
Los indices del elemento igual 2 son (array([1, 3]),)
Los indices del elemento igual 4 son (array([5, 7]),)


8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [44]:
array4 = np.random.randint(0, 50, (3,5))
array4

array([[44, 12, 38, 12, 43],
       [36,  7, 37, 35,  1],
       [22,  3, 16, 36, 43]])

In [46]:
array[(array < 10) | (array > 40)]

array([7, 2, 2, 7, 4, 9, 4, 9, 8])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [52]:
array5 = np.random.randint(5, 9, (5,3)) + np.random.random_sample((5,3))

array5

array([[8.8256391 , 5.21111635, 5.01804408],
       [5.62701912, 7.68657166, 5.39647265],
       [6.37017841, 5.45100899, 6.57119966],
       [5.97504026, 7.168294  , 7.85560909],
       [8.57253324, 8.14938292, 8.92681966]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20
- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [53]:
array6 = np.random.randint(1, 20, (2,4,7))
array6

array([[[ 9,  8, 19,  9,  9,  7,  6],
        [ 5,  1,  1,  2,  6, 12,  3],
        [16, 13,  5,  7,  1,  2, 17],
        [ 9,  1,  7,  3, 17,  2, 19]],

       [[18,  8, 11,  3, 10, 12,  3],
        [ 5, 16, 14,  9, 11, 15,  2],
        [19,  6, 16,  5, 11,  9, 19],
        [12, 13,  8,  5,  3, 14,  5]]])

In [54]:
array6 = np.reshape(array6, (4,7,2))
array6

array([[[ 9,  8],
        [19,  9],
        [ 9,  7],
        [ 6,  5],
        [ 1,  1],
        [ 2,  6],
        [12,  3]],

       [[16, 13],
        [ 5,  7],
        [ 1,  2],
        [17,  9],
        [ 1,  7],
        [ 3, 17],
        [ 2, 19]],

       [[18,  8],
        [11,  3],
        [10, 12],
        [ 3,  5],
        [16, 14],
        [ 9, 11],
        [15,  2]],

       [[19,  6],
        [16,  5],
        [11,  9],
        [19, 12],
        [13,  8],
        [ 5,  3],
        [14,  5]]])